### ISSUE TITLE
Support for multi-lingual Drupal with prefix-based translation

### ISSUE THREAD

**Issue by mlutfy** [agiliway/com.agiliway.civimobileapi#1]
Very nice app! Thank you!

I had a small issue making it work with our multi-lingual Drupal7 CiviCRM site.

* If I enter: https://demo.symbiotic.coop as the main URL, the app gets a 302 (redirect) response to /fr/.
* If I enter: https://demo.symbiotic.coop/fr as the main URL, it gets a bit further, but then gets a 404, because https://demo.symbiotic.coop/fr/index.php does not exist.

I think that using only `https://demo.symbiotic.coop/?q=[...]` (without the `index.php`) would fix the issue.

You can test on our demo site, https://demo.symbiotic.coop, the login is demo/demo.

(I tried working around it with nginx aliases. I managed to get login to work, but then other requests failed afterwards)

**Comment by AWG-Bohdan** [comment]
Hi Mathieu,

- The new version of mobile app now should work with your site.
- On September 1st we are planning to release version which will support multi-lingual CRM.

**Comment by mlutfy** [comment]
Hi @AWG-Bohdan, we tested the new version and it indeeds works well on a multi-lingual CiviCRM/Drupal. Thank you!
