### ISSUE TITLE
Warning in the Contact Summary

### ISSUE THREAD

**Issue by kainuk** [agiliway/com.agiliway.civimobileapi#10]
CiviMobile extends the CiviCRM Api, with the help of the apiWrappers hook. The hook, however, is also invoked directly from the CiviCRM screens. In version 5.13.4 this causes the following warning.
![mobileApiWarning](https://user-images.githubusercontent.com/14834891/58024248-0a109f00-7b12-11e9-9d39-cf2f0709b8d9.png)

**Comment by andriystabryn** [comment]
Hi @kainuk ,
Thank you! Can you send me a link or steps how to reproduce the problem?

**Comment by kainuk** [comment]
Hi @andriystabryn, the warning appeared for the first time after the upgrade to 5.13.4 (the latest security release). It just shows up above the contact summary
![contactSummary](https://user-images.githubusercontent.com/14834891/58025157-257ca980-7b14-11e9-9ac3-fe4cff212113.png)

**Comment by savionlee** [comment]
@kainuk error is also showing up in my WordPress installation.

**Comment by kainuk** [comment]
@savionlee I made a PR for this (https://github.com/agiliway/com.agiliway.civimobileapi/pull/11). You can install it and test if it makes a difference.

**Comment by sishea** [comment]
I wrapped the _foreach()_ with _if (is_array($result['values']))_.

It has fixed the warning and no adverse affects that I've noticed yet...

**Comment by kainuk** [comment]
FYI https://civicrm.stackexchange.com/questions/30984/error-on-enabling-civimobileapi-extension

**Comment by andriystabryn** [comment]
fixed in 3.2.2 version

**Comment by kainuk** [comment]
:-)
