### ISSUE TITLE
info.xml file reports compatibility as version 4.7

### ISSUE THREAD

**Issue by Upperholme** [agiliway/com.agiliway.civimobileapi#12]
Should it also report as supporting 5.x?

**Comment by andriystabryn** [comment]
<ver> tags now imply forward compatibility when the version specified is 4.7 or higher. (e.g. an extension declaring <ver>5.1</ver> is displayed on 5.2, 5.3 etc. but not on 5.0.) 
https://docs.civicrm.org/dev/en/latest/extensions/info-xml/

**Comment by andriystabryn** [comment]
I'm going to close this issue, if you have question feel free to reopen
