### ISSUE TITLE
Drupal 7 login error

### ISSUE THREAD

**Issue by Upperholme** [agiliway/com.agiliway.civimobileapi#15]
Just installed version 3.2 of the extension on a Drupal 7/Civi 5.13.5 site. On attempting to log in using the iOS app I get the error message "The extension is too old. Contact the administrator to upgrade CiviMobile API extention (sic) to the latest version"

**Comment by Upperholme** [comment]
Wondering whether I need an - as yet unavailable - update to the mobile app as well to sync with the updated extension?

**Comment by Upperholme** [comment]
Update: Getting the same error on a second D7 site, also with the 3.2 extension installed. So right now I can't use the mobile app with any Wordpress or D7 sites.

**Comment by andriystabryn** [comment]
Hi @Upperholme ,
today we released fixes for WP (https://github.com/agiliway/com.agiliway.civimobileapi/issues/8)
Can you write me more about the D7 bug? Maybe you can share access to website, so we can faster find a problem ? 
My email is andriy.stabryn@agiliway.com

**Comment by Upperholme** [comment]
On the Drupal side of things, I had CiviMobile working well on one site using version 3.1 of the extension. I updated to 3.2 and it has stopped working, giving the error report in the first post of this issue. I'll email with the domain name.

**Comment by andriystabryn** [comment]
@Upperholme do you have any news?

**Comment by netzih** [comment]
From my experience where it was saying this extension is too old I had to update the directory to be com.agiliway.civimobileapi (instead of the default com.agiliway.civimobileapi-master when downloading zip file directly from github)

**Comment by andriystabryn** [comment]
@Upperholme I'm going to close the issue. If you still have some problem please reopen it
