### ISSUE TITLE
CiviMobile tab for logging out is confusing

### ISSUE THREAD

**Issue by jmcclelland** [agiliway/com.agiliway.civimobileapi#17]
Hi - Thanks for the great extension and app!

We recently discovered that seemingly every contact in the database now has a CiviMobile tab with a "Logout From Mobile" button. 

I dug around and it looks like this is a useful way to log people out of the mobile app.

But I was confused because:

1. It seems to show up for every contact, not just ones that have an api key
2. There is very little explanation for what it does. If it could be re-coded to only show up for people who have an api_key, then there could be an explanation at the top along the lines of: "This contact has logged in using the CiviCRM mobile app. Click the buttom below to log them out."

**Comment by andriystabryn** [comment]
Hi @jmcclelland ,
thanks for your interest!
"Logout from mobile" is for security. All users can log out themself from their devices. Admin also can logout any user from him/her device. 

So, I guess you are using admin access. If you will try to login as a simple user you will be able just to logout yourself.

**Comment by jmcclelland** [comment]
Thanks for the explanation - and I like the feature. 

Would you be open to a patch that hides the "CiviMobile" tab on a user's dashboard if they do not have an api key set?

**Comment by andriystabryn** [comment]
@jmcclelland we are planning to expand the functionality on this tab. 
But, maybe you are right and we have to hide the tab or to show a message " you are not using CiviMobile...."

**Comment by jmcclelland** [comment]
Yeah, that's the idea. It does give the impression that every contact in the database is using civimobile!

**Comment by andriystabryn** [comment]
@jmcclelland we have released a new version. Please upgrade

**Comment by jmcclelland** [comment]
Thank you!
