### ISSUE TITLE
"this extension is too old. contact the administrator to upgrade CiviMobile API extension to the latest version"

### ISSUE THREAD

**Issue by netzih** [agiliway/com.agiliway.civimobileapi#19]
Keep getting this error when trying to login.
It worked a while back but lately for the last while Iv'e been getting this error.
I'm running civi 5.15 on WP 5.2.2.
Installed civimobileapi 3.2.2 and have the wordpress fix plugin installed too.

**Comment by andriystabryn** [comment]
@netzih unfortunality new version of CiviCRM doesn't work with our plugin.
Please do following:

1. update CIviMobileAPI extension to last version version (https://github.com/agiliway/com.agiliway.civimobileapi/releases)
2. install this WP plugin https://github.com/mecachisenros/civicrm-wp-rest
3. remove our old WP plugin CiviMobileAPIFix

And try to login one more time!

**Comment by netzih** [comment]
Tried installing the latest release and when logging in now I'm getting this extension is too old. Contact administrator.

**Comment by andriystabryn** [comment]
@netzih what version do you have?

**Comment by netzih** [comment]
I'm on 4.0 amd civi 5.15
Now when trying to login I'm getting "this extension is too old. contact the administrator to upgrade CiviMobile API extension to the latest version.

**Comment by netzih** [comment]
I had to change the directory from "com.agiliway.civimobileapi-master" to "com.agiliway.civimobileapi" and now I was able to log in.
However when trying to add an activity I'm getting server API error.

**Comment by netzih** [comment]
Moved directory from "com.agiliway.civimobileapi-master" to "com.agiliway.civimobileapi"and it works.
