### ISSUE TITLE
enable extension requires token?

### ISSUE THREAD

**Issue by Rar9** [agiliway/com.agiliway.civimobileapi#2]
enabling this new extension in my civicrm 5.4.0 i get a new tab under contacts called 

Contact Push Notification
  which  requires these fields that prevent me from saving my contacts

![image](https://user-images.githubusercontent.com/2239608/43690423-0a12d1fc-990a-11e8-999f-f0f28fbb4144.png)

**Comment by MikeyMJCO** [comment]
I'm seeing the same issue on a Drupal 7.59 / CiviCRM 5.4.0 site. Can provide demo login details on request - it's a test site.

**Comment by sleewok** [comment]
These fields should NOT be required. Can the dev please change this? We should not have to add this information when creating a contact.

**Comment by AWG-Bohdan** [comment]
We just released new version and removed this 'token' field. 
Please install new version and execute the update script  
<img width="531" alt="v1 1-update" src="https://user-images.githubusercontent.com/31275766/43950800-0db8e4ca-9c9a-11e8-9fa0-d1fcbc93077a.png">

**Comment by MikeyMJCO** [comment]
Thanks @AWG-Bohdan and keep up the great work - CiviMobile is a fantastic asset for the entire CiviCRM community.
