### ISSUE TITLE
Registring for a paid event

### ISSUE THREAD

**Issue by eth4ever** [agiliway/com.agiliway.civimobileapi#23]
Hi there, Thanks for the great job on version 4.0 of civimobileapi. Lots of new functionality. I installed it on Drupal 7/Civi 5.0. Login in is fine. (see #8). Registering to an event is great.

But when it comes to a paid event, I can choose the amount and I can register, but I can not pay. Strange enough I got registered to the event, although I did not pay. Maybe it has to do with the payment extension (we use Omnipay multiprocessor support), maybe it has to with the payment provider, maybe it has to do with Apple (tested on a iPhone Xr), since they don't like in app purchases that do not use the apple ID payment solution.

So the question is: Should it be possible to regsiter to a paid event (and pay before the registration is confirmed)? Or is that a bridge to far. In that case it should not be possible to register within the app to a paid event.

**Comment by netzih** [comment]
It's has nothing to do with Apple.
I have an android and it does not collect the payment either 
It just registers the contract.

**Comment by andriystabryn** [comment]
@eth4ever we have fixed the problem. It was wrong email previously. Now you will see the email "Pending pay later".
