### ISSUE TITLE
Event: extra field not showing up

### ISSUE THREAD

**Issue by eth4ever** [agiliway/com.agiliway.civimobileapi#24]
When you register to an event extra fields as on the registration form in your browser, are not shown in the app. Only name and e-mail adres are shown. Is that correct?

Often we ask for extra information i.e. dieet requests.

**Comment by andriystabryn** [comment]
@eth4ever Do you mean custom fields?

**Comment by eth4ever** [comment]
Yes, custom fields. But most of the time we also ask for stand civi fields like address, phone, etc.

**Comment by andriystabryn** [comment]
Unfortunately, custom fields are not available yet for events.
Currently we are writing custom fields for contact.

If you have some ideas what will be most useful CiviCRM functionality feel free to write me andriy.stabryn@agiliway.com

**Comment by eth4ever** [comment]
I think every event is diffirent, but I think standard contact fields (address, phone etc.) and custom events fields are the ones that are usefull for every one.

**Comment by AWG-Bohdan** [comment]
Hello,

We have moved the project space for CiviMobileaAPI to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/civimobileapi

All issues have been migrated to: https://lab.civicrm.org/extensions/civimobileapi/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
