### ISSUE TITLE
Events: QR-code doesn't show

### ISSUE THREAD

**Issue by eth4ever** [agiliway/com.agiliway.civimobileapi#25]
The QR-code for the participant doesn't show in the app or in the confirmation e-mail.
I tested with a free event (no payments required), received an e-mail with a pictured but apparently the QR-code couldn't be downloaded.

I found the url to the QR-code in the registration of the participant.
http://mysubdomain.mysite.org/civicrm/file?reset=1&id=338&eid=803
The file is stored at: sites/default/files/civicrm/custom/participantId_803.png
Logged in to Civi I was able to download the file, logged out I wasn't. So it seems to be an access right issue.

How can I solve this?

**Comment by netzih** [comment]
Having the same issue.
Registered participant they got an email and where was supposed to be the qr image is blank. 
Tried going to the participant on the web and when clicking on the file url in getting file url is invalid.... 
QR codes seems to not be working.

**Comment by VoRCeK** [comment]
Same here.. I can confirm the same issue.  QR Code images are being created, but they are not showing in confirmation emails.

**Comment by andriystabryn** [comment]
@eth4ever @netzih @VoRCeK we have release a new extension with a fix. Sorry, but now you can use the functionality

**Comment by VoRCeK** [comment]
This still isn't working for me and we are using latest CiviMobileAPI 4.0.2.  Although.. we are running CiviCRM 5.13.5

**Comment by netzih** [comment]
Still not working on 4.0.2 Civi 5.15.1

**Comment by andriystabryn** [comment]
Hi @VoRCeK and @netzih 
Thanks for your comments! We've found a bug and released a 4.0.3 version https://github.com/agiliway/com.agiliway.civimobileapi/releases/tag/v4.0.3 .
Could you try one more time? 
Note that only new tickets will have QR codes.

**Comment by VoRCeK** [comment]
Mine is still not working..  I'm not going to presume I know why...  but, others have discussed similar issues elsewhere and I think they might be related:

[CIVI-SA-2019-01](https://civicrm.org/advisory/civi-sa-2019-01-weak-access-control-for-file-attachments)
[Get URL of custom image field](https://civicrm.stackexchange.com/questions/28754/get-url-of-custom-image-field)

the url created with this extension is
> http://mydomain.org/civicrm/file?reset=1&id=5&eid=105

which does not have a signed access token included (fcs=)
also, the generated url is still http although my site's traffic is rerouted to https

**Comment by andriystabryn** [comment]
@VoRCeK do you have 4.0.3 extension? We've fixed "https" bug in 4.0.3

**Comment by VoRCeK** [comment]
@andriystabryn yes, I am using 4.0.3 extension.. I have elected for the extension to update automatically.

**Comment by netzih** [comment]
I am on v4.0.3 as well and it isn't working.
I'm on wp, can that be a problem?

**Comment by andriystabryn** [comment]
Guys, could you send me more details:

1. what CMS and it version
1. CiviCRM version

Would be perfect if you can send me credentials to your website in case there are no any sensitive information.

**Comment by netzih** [comment]
> Guys, could you send me more details:
> 
> 1. what CMS and it version
> 2. CiviCRM version
> 
> Would be perfect if you can send me credentials to your website in case there are no any sensitive information.

I'm on the latest versions of both. 
I'm on wp5.2.2 and civicrm 5.15.2

**Comment by VoRCeK** [comment]
@andriystabryn here's my setup..

Drupal version:  7.67
CiviMobileAPI:   4.0.3
PHP version:      7.2.20

**Comment by andriystabryn** [comment]
@VoRCeK @netzih , 
We've found one permission, which prohibits access to QRcode image. 
Could you check if your user has "CiviCRM: access uploaded files" permission ?
If no, please enable it and try to register one more time, only new registration should have QR image.

**Comment by VoRCeK** [comment]
@andriystabryn  Confirmed: YES that Drupal permission is active for all roles.  I also rebuilt permission and tried again, just in case.. still did not work.

**Comment by AWG-Bohdan** [comment]
Hello,

We have moved the project space for CiviMobileaAPI to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/civimobileapi

All issues have been migrated to: https://lab.civicrm.org/extensions/civimobileapi/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
