### ISSUE TITLE
Can't load data

### ISSUE THREAD

**Issue by netzih** [agiliway/com.agiliway.civimobileapi#26]
When using thr civimobile app it works fine.
But than when I close the app and go back a little while later it doesn't let me do anything. I can see the main stuff on the screen but nothing new and cannot add/edit anything. 
I need to log out and log back in to get it working again (until I leave the app)
It should keep me logged in even after leaving the app for a while (or at least take me to the login screen so I don't need to log out myself).

**Comment by andriystabryn** [comment]
Hi @netzih . It is something specific to your phone or maybe some settings on your phone. 
The app keeps user logged in always.

**Comment by netzih** [comment]
I do not know.
It's on 3 different sites that I set up all the same way.
Maybe it's a server issue that is logging the app out.

**Comment by andriystabryn** [comment]
I guess it depends on your phone, not a server. Could you try to install an app on another phone ?

**Comment by netzih** [comment]
No, each website is using a different server and a different phone, (2android one iphone) .

**Comment by andriystabryn** [comment]
Can you send me a video to andriy.stabryn@agiliway.com.
It's a bit strange, How do you log out if the app doesn't work?

**Comment by netzih** [comment]
I just logged on so it will work for the next couple of hours.
When I open the app I get server api error and it asks me if I want to send the info to developers... 
The data that was on the screen that was loaded already (few current days on calendar and first bunch of contacts etc.) I can access but when trying to refresh or load more contacts it doesn't let me.

**Comment by AWG-Bohdan** [comment]
Hello,

We have moved the project space for CiviMobileaAPI to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/civimobileapi

All issues have been migrated to: https://lab.civicrm.org/extensions/civimobileapi/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
