### ISSUE TITLE
Errors on Phone Number Entry

### ISSUE THREAD

**Issue by danfish** [agiliway/com.agiliway.civimobileapi#27]
When adding a phone to a new or existing contact, the characters + - and . cause an error.
1 phone number like +1.123.456.7890 errors while 1234567890 does not.  Would like to enter phone using standard formats.
![Screenshot (Jul 27, 2019 5_55_10 PM)](https://user-images.githubusercontent.com/3443123/62000915-4de6ce00-b098-11e9-9ba3-7bb733edbd63.png)
![Screenshot (Jul 27, 2019 5_55_40 PM)](https://user-images.githubusercontent.com/3443123/62000916-5808cc80-b098-11e9-9415-2b642601ca6c.png)

**Comment by andriystabryn** [comment]
Hi @danfish, will fix it in the next release!

**Comment by danfish** [comment]
Thank you!

**Comment by andriystabryn** [comment]
@danfish it is already available on Android and will be available on iOS soon (on review now)

**Comment by AWG-Bohdan** [comment]
Hello,

We have moved the project space for CiviMobileaAPI to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/civimobileapi

All issues have been migrated to: https://lab.civicrm.org/extensions/civimobileapi/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
