### ISSUE TITLE
Extension puts script code before all other page content (on Wordpress)

### ISSUE THREAD

**Issue by AlphaDE** [agiliway/com.agiliway.civimobileapi#3]
After installing the extension and the associated plugin for Wordpress, I got JQuery errors and broken pages. I discovered that the extension/the Wordpress plugin put java script code before all other page content and thus before the "OnLoad" statement ensuring the availability of the JQuery library.

**Comment by adam-devapp** [comment]
+1. The CiviCRM jQuery files don't appear to load on the latest version (5.12.4) when this module is enabled with a jQuery undefined error.

**Comment by mcherkes** [comment]
Dear @adam-devapp and @AlphaDE thanks for your interest in CiviMobileApp. We have already updated CiviMobile App extension with latest fixes. So, please download the latest version and try it.

**Comment by andriystabryn** [comment]
@adam-devapp and @AlphaDE can you check again with last version of extension?
