### ISSUE TITLE
Cannot login on a Drupal8 CiviCRM site

### ISSUE THREAD

**Issue by mlutfy** [agiliway/com.agiliway.civimobileapi#34]
The mobile application seems to use the following type of URL:

```
"POST /index.php?q=civicrm/civimobile/auth&page=CiviCRM
```

The `q` parameter is deprecated in Drupal8. This results in a 302 redirect on my installation, and the login fails.

Could you instead use:

```
"POST /civicrm/civimobile/auth?page=CiviCRM
```

Thank you!

**Comment by AWG-Bohdan** [comment]
Hi @mlutfy
Our main developer is on vacation and we will look at this issue in 2 weeks.
Regards, Bohdan

**Comment by AWG-Bohdan** [comment]
Hello,

We have moved the project space for CiviMobileaAPI to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/civimobileapi

All issues have been migrated to: https://lab.civicrm.org/extensions/civimobileapi/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!

**Comment by andriystabryn** [comment]
Just small updates, 
@mlutfy CiviMobile doesn't support Drupal 8.
