### ISSUE TITLE
The extension is too old error message

### ISSUE THREAD

**Issue by sunnycs121** [agiliway/com.agiliway.civimobileapi#35]
CMS: Drupal
CiviCRM Version: 5.13.6
CIVIMOBILEAPI Version: 4.1.1

When trying to login in android version of application, it gives error "The Extension is too old. Please contact administrator....."

With CiviCRM version 5.13.6, extension version 3.2.1 appears to work fine.

**Comment by AWG-Bohdan** [comment]
Hi
Could you check that extension folder name is com.agiliway.civimobileapi without “-4.0” or “-master” or any another suffix?
