### ISSUE TITLE
civicrm-wp-rest causing cron to bomb

### ISSUE THREAD

**Issue by guyiac** [agiliway/com.agiliway.civimobileapi#38]
Once I loaded the Civimobile API and the CiviCRM WP REST API, my cron started bombing with this message:

Catchable fatal error: Argument 1 passed to CiviCRM_WP_REST\Autoloader::add_source() must be an instance of CiviCRM_WP_REST\string, string given, called in /..../..../..../..../wp-content/plugins/civicrm-wp-rest/civicrm-wp-rest.php on line 42 and defined in /..../..../..../..../wp-content/plugins/civicrm-wp-rest/src/Autoloader.php on line 64

**Comment by AWG-Bohdan** [comment]
Hello,

Could you recreate this issue but in Lab CiviCRM repository ? We have move project to new repo https://lab.civicrm.org/extensions/civimobileapi/issues 

Regards,
Bohdan

**Comment by andriystabryn** [comment]
Hi @guyiac

The bug is inside a civicrm-wp-rest plugin. Could you create an issue there https://github.com/mecachisenros/civicrm-wp-rest ? 

I will close the ticket here. If you still need a help you can write me andriy.stabryn@agiliway.com
