### ISSUE TITLE
No link in Github description to Gitlab

### ISSUE THREAD

**Issue by adanielvv** [agiliway/com.agiliway.civimobileapi#4]
> Please contact our CiviCRM team on civicrm@agiliway.com or report your issues/suggestions directly to CiviMobile project in GitLab

Source: https://civicrm.org/blog/skornien/civimobile-a-native-mobile-application-for-civicrm
Link in source: https://lab.civicrm.org/Agiliway/CiviMobile
Correct link: https://lab.civicrm.org/partners/Agiliway/CiviMobile
Link to issues: https://lab.civicrm.org/partners/Agiliway/CiviMobile/issues

(neither is there a link to contribute on https://civimobile.agiliway.com/)

**Comment by mlutfy** [comment]
The `/partners` gitlab space is meant for partner-specific forks.

For official extensions, please add it under https://lab.civicrm.org/extensions (you can ping `@bgm` on mattermost to create a new project space in https://chat.civicrm.org/civicrm/channels/extensions)

**Comment by adanielvv** [comment]
What I meant is that it would be helpful to have a link on the github readme to the CiviCRM gitlab issues page.

**Comment by mlutfy** [comment]
oh ok, yep. Bohdan did the import today, and since this topics comes up from time to time, we posted some guidelines here: https://lab.civicrm.org/extensions/extensions-directory/wikis/import-from-github
