### ISSUE TITLE
The extension is too old

### ISSUE THREAD

**Issue by rulosant** [agiliway/com.agiliway.civimobileapi#43]
We have a fresh Drupal 7.69 install
We have installed CiviMobileAPI using the CiviCRM installer: V 5.0.1

Te directory doesn't have any suffix: /sites/default/files/civicrm/ext/com.agiliway.civimobileapi

We downloaded the mobile app from playstore: v5.0

We are using http, not https

do you have any idea?

**Comment by andriystabryn** [comment]
HI @rulosant ,

We are currently investigating this problem. 
If you can send me access to your system it may help us to faster investigate the problem.

My email is andriy.stabryn@agiliway.com

**Comment by dgbdgb** [comment]
+1, when using CiviCRM 5.23, CiviMobileAPI 5.0.1, Multisite Wordpress 5.3.2

**Comment by andriystabryn** [comment]
@dgbdgb Can you also share your credentials? 

@rulosant thanks, we are investigating the problem

**Comment by andriystabryn** [comment]
@rulosant In your case this is problem in Website URL. We don't support subfolders https://website.com/SUBFOLDER. Only clean domains and subdomains.
We are going to release subfolder support in next release

**Comment by rulosant** [comment]
Thank You @andriystabryn! I will try moving the site to a clean domain

**Comment by andriystabryn** [comment]
I've closed the issue

**Comment by andriystabryn** [comment]
We have implemented a subfolder support in next release (5.1). So all of you will be able to use soon (next week)
