### ISSUE TITLE
iPhone CiviMobile app issue: "Please install CiviMobile extension in your CiviCRM"

### ISSUE THREAD

**Issue by ffacemire** [agiliway/com.agiliway.civimobileapi#44]
Hi Bohdan,
I am getting the same error as davyrhys experienced (comments in a closed thread from Sept '19) on my iPhone CiviMobile app: "Please install CiviMobile extension in your CiviCRM".

I am only now in the process of configuring CiviCRM and CiviMobile, having just installed CiviCRM using the Bitnami Stack for Google Cloud.  The installed versions are: Drupal  7.69/CiviCRM 5.23.4/CiviMobileApi 5.0.1

I can connect to my CiviCRM URL, but when I enter my username and password on the user login page, I get the above error in red font.

I appreciate any assistance you can provide.

_Originally posted by @ffacemire in https://github.com/agiliway/com.agiliway.civimobileapi/issues/30#issuecomment-606980692_

**Comment by amorphous** [comment]
the docs do say that the ext directory has to be precise, and should be com.agiliway.civimobileapi

renaming the extension fixed the problem for me.

**Comment by AWG-Bohdan** [comment]
We have moved the project space for CiviMobileAPI to CiviCRM's Gitlab. https://lab.civicrm.org/extensions/civimobileapi
