### ISSUE TITLE
push notifications

### ISSUE THREAD

**Issue by Upperholme** [agiliway/com.agiliway.civimobileapi#45]
I've just done a back-up of my Civi database, and note that it is stuffed with nearly 20 million push notification records, which I assume are being generated by this extension.

I'm not clear why all these records are being created. Can I toggle them off if I don't need them?

Do these records always build up, or are they deleted if a mobile connected user views or clears them?

Can I mass delete them form the database safely?

**Comment by andriystabryn** [comment]
Hi @Upperholme ,
Yes, you may safely remove them from database. By the way if you configure cron on your server it will clear the records older then 90 days.

**Comment by Upperholme** [comment]
Thanks for this.

I have a cron running, I'll check the scheduled jobs.

**Comment by andriystabryn** [comment]
I'll close the issue. If you still have questions feel free to write me.
