### ISSUE TITLE
Extension doesn't work when installed in vendor folder

### ISSUE THREAD

**Issue by Shwele** [agiliway/com.agiliway.civimobileapi#47]
Hello guys,

We have Drupal 7 implementation with Aegir system and there are issues with vendor folder when we want to use some extension globally for all clients.

Yours in particular is giving error that its not installed correctly and it is not possible to make it work and load up for all clients from that folder.

Hopefully this is enough to be noted as issue and for changes to be pushed in new version.

Kind regards,
Nikola

**Comment by andriystabryn** [comment]
Hello @Shwele ,
Thank you for your request. We are going to add this feature to our backlog.

**Comment by AWG-Bohdan** [comment]
We have moved the project space for CiviMobileAPI to CiviCRM's Gitlab. https://lab.civicrm.org/extensions/civimobileapi
