### ISSUE TITLE
Deprecated function called

### ISSUE THREAD

**Issue by eileenmcnaughton** [agiliway/com.agiliway.civimobileapi#48]
This line

https://github.com/agiliway/com.agiliway.civimobileapi/blob/master/CRM/CiviMobileAPI/Utils/ActivityType.php#L95

is calling a function that is unused & deprecated in core - at some point it will be removed. Ideally you should use the api - which is the supported interface. But, at a pinch you could copy the function into your extension until you do remove it (but put it on the class calling it, not a copy of the core class)

**Comment by AWG-Bohdan** [comment]
We have moved the project space for CiviMobileAPI to CiviCRM's Gitlab. https://lab.civicrm.org/extensions/civimobileapi
