### ISSUE TITLE
Lots of PHP error logs

### ISSUE THREAD

**Issue by IowaBoy1** [agiliway/com.agiliway.civimobileapi#50]
Drupal 7.78
Civi 5.28.2
CiviMobile 5.4.0

We have disabled the extension because it is filling our Report Logs with pages of error messages. 

Notice: Undefined index: total_amount in CRM_CiviMobileAPI_ApiWrapper_Contribution->fillFormatTotalAmount() (line 90 of /sites/default/files/civicrm/extensions/com.agiliway.civimobileapi/CRM/CiviMobileAPI/ApiWrapper/Contribution.php).

Notice: Undefined index: version in CRM_CiviMobileAPI_ApiWrapper_Contribution::isApiVersion3() (line 42 of /sites/default/files/civicrm/extensions/com.agiliway.civimobileapi/CRM/CiviMobileAPI/ApiWrapper/Contribution.php)

Notice: Undefined index: currency in CRM_CiviMobileAPI_ApiWrapper_Contribution->fillFormatTotalAmount() (line 90 of /sites/default/files/civicrm/extensions/com.agiliway.civimobileapi/CRM/CiviMobileAPI/ApiWrapper/Contribution.php).

Warning: stristr() expects parameter 1 to be string, array given in CRM_CiviMobileAPI_ApiWrapper_Contribution->fillFormatTotalAmount() (line 84 of /sites/default/files/civicrm/extensions/com.agiliway.civimobileapi/CRM/CiviMobileAPI/ApiWrapper/Contribution.php).

Warning: stristr() expects parameter 1 to be string, array given in CRM_CiviMobileAPI_ApiWrapper_Contribution->fillFinancialTypeName() (line 59 of /sites/default/files/civicrm/extensions/com.agiliway.civimobileapi/CRM/CiviMobileAPI/ApiWrapper/Contribution.php).

These repeat over and over.

**Comment by AWG-Bohdan** [comment]
Hi @lowaBoy1 ! Thank you for your issue. We`ve fixed this problem in CiviMobileAPI 5.5.2.1. We will be very happy if you start using CiviMobile again. We also moved our project to GitLab https://lab.civicrm.org/extensions/civimobileapi . 

If you have any questions feel free to write us info@civimobile.org.

**Comment by IowaBoy1** [comment]
That did seem to fix it!! Thanks
