### ISSUE TITLE
performance issues with the events dashboard

### ISSUE THREAD

**Issue by thomst** [agiliway/com.agiliway.civimobileapi#51]
We observed on several CiviCRM environments that an activated civimobile extension worsened the performance loading the events dashboard significantly.
The loading time of the dashboard goes up from ~2 sec to ~15 sec and more.

The versions on the effected environments where:
CiviCRM: 5.28.3
civimobileapi: 5.5.2.1 and 5.5.2

**Comment by AWG-Bohdan** [comment]
Hi @thomst . Thank you for your comments. We fixed this issue and will release next version of CiviMobileAPI extension. 
Please note that we moved our project to GitLab https://lab.civicrm.org/extensions/civimobileapi . 

If you have any questions feel free to write us info@civimobile.org.

**Comment by AWG-Bohdan** [comment]
We have moved the project space for CiviMobileAPI to CiviCRM's Gitlab. https://lab.civicrm.org/extensions/civimobileapi
