### ISSUE TITLE
App crashing when changing server

### ISSUE THREAD

**Issue by vitius1** [agiliway/com.agiliway.civimobileapi#52]
1. problem: 
When I log-out and click on "back" for change server, App immediately crash and even can't reopen it. I must reinstall whole app.

2. problem:
For my second civicrm site I can't even log-in. The app crashing same way like in first problem and must reinstall app. 

For both problems helps download older version of app. (version 5.2 or version 5.3 works fine)

I have Samsung galaxy S8 with android 9.
I also try with pc emulator "BlueStacks" and have same problem.

**Comment by AWG-Bohdan** [comment]
We have moved the project space for CiviMobileAPI to CiviCRM's Gitlab. https://lab.civicrm.org/extensions/civimobileapi
