### ISSUE TITLE
Rest url is not correct.

### ISSUE THREAD

**Issue by rsessa** [agiliway/com.agiliway.civimobileapi#53]
Hello! I have installed civimobileAPI as indicated on the civimobile website and I cannot log in with an administrator user (API error)
I have drupal 9.3.9
Civil 5.45.5
CiviMobile 5.9
PHP 7.4.28
MariaDB 10.5.15
The address indicated in the checklist does not exist /libraries/civicrm/core/extern/rest.php

**Comment by AWG-Bohdan** [comment]
Project moved to GitLab https://lab.civicrm.org/extensions/civimobileapi/-/issues/70
