### ISSUE TITLE
can't close get app bar.

### ISSUE THREAD

**Issue by Rar9** [agiliway/com.agiliway.civimobileapi#7]
in the last version there is no button to hide the footer GET Android/IPhone APP bar.

**Comment by AWG-Bohdan** [comment]
We are working on this issue and will deploy fix soon

**Comment by mcherkes** [comment]
Dear @Rar9 We have already updated CiviMobile App extension and CiviMobile App with the latest fixes. So, please download the latest version and try it.

**Comment by Rar9** [comment]
Yes saw this 2 days ago, and X showed, but im getting new warning now.  Will post when i have the time

**Comment by andriystabryn** [comment]
fixed in 3.2.2 version

**Comment by andriystabryn** [comment]
fixed in 3.2.2 version
