### ISSUE TITLE
Doesn't activate 2FA on login

### ISSUE THREAD

**Issue by clement888** [agiliway/com.agiliway.civimobileapi#9]
Congratulation on the work, this is very exciting!

I have installed this on our setup which is protected by DUO Security 2 Factor Authentication for login.  I see that there is no prompting of the 2FA but the app was able to access the data nonetheless.  Can you shed some light on this ? Thanks.

WordPress 5.0.4 CIVICRM 5.10.4 Ubuntu 18.04.1 Apache2

**Comment by mcherkes** [comment]
Dear @clement888 thanks for your interest in CiviMobile App. We support only native CMS authentication. We don’t support SSO. We don’t support Central Authentication Service (CAS), 2FA and any other SSO implementations. I'm not sure that we will implement such things in the near future.

**Comment by AWG-Bohdan** [comment]
Hello,

We have moved the project space for CiviMobileaAPI to CiviCRM's Gitlab.
This includes both the issue tracking and support, and merge requests.

The new URL is: https://lab.civicrm.org/extensions/civimobileapi

All issues have been migrated to: https://lab.civicrm.org/extensions/civimobileapi/issues

If you do not already have an account on CiviCRM's Gitlab, you can create an account
by registering on https://civicrm.org/user

Thank you!
